### ISSUE TITLE
cannot set stuff up

### ISSUE THREAD

**Issue by myst-rblx** [UncertainProd/FnF-Spritesheet-and-XML-Maker#1]
C:\Users\elias\Documents\FnF-Spritesheet-and-XML-Maker-master\FnF-Spritesheet-and-XML-Maker-master>pip install -r requirements.txt
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by UncertainProd** [comment]
You should install Python first and during the installation, make sure that "pip" is selected under "Optional Features". That'll install pip as well as python.

**Comment by DaBlueNinja03** [comment]
Hello? I have a question

**Comment by DaBlueNinja03** [comment]
Nvm
