### ISSUE TITLE
Existing spritsheet and xml crash

### ISSUE THREAD

**Issue by Playertrip777** [UncertainProd/FnF-Spritesheet-and-XML-Maker#30]
**Describe the bug**
Importing the existing spritsheet and their xml causes the program to crash.

**To Reproduce**
Open the program, go to FIle > Import esisting Spritsheet and XML, then import the existing spritsheet and their xml (like Daddy Dearest).

**Expected behavior**
The spritsheet was supposed to split into individual images,

**Screenshots**
None

**Application ran from exe or from source?**
 - OS: Windows
 - Executable from Gamebanana

**Comment by UncertainProd** [comment]
Can you send the spritesheet and xml for which it didn't work?

**Comment by Playertrip777** [comment]
https://drive.google.com/drive/folders/1K1dxpFtR5O8POwy8CV7KDpmDlpUD1dlG?usp=sharing

**Comment by UncertainProd** [comment]
It seems to work when I tried it, did you use version 4.0 or was it older?

**Comment by Playertrip777** [comment]
The latest version works! Thank you!
