### ISSUE TITLE
Sprites are scambled in the png when generating an xml

### ISSUE THREAD

**Issue by EnderSpr1tz** [UncertainProd/FnF-Spritesheet-and-XML-Maker#33]
**Bug**
When generating an xml, the sprites are scrambled in the png and dosent work on psych engine

**To Reproduce**
I just opened the app/exe, loaded an existing sprite and xml, added new sprites without touching existing, saw everything in the preview and xml structure looked as intended and generated a new xml

**Expected behavior**
I expected to have a working sprite sheet and xml

**Screenshots**
![image](https://user-images.githubusercontent.com/97370586/148665974-b57ad07c-f85c-480c-b916-f22d2939e327.png)
![image](https://user-images.githubusercontent.com/97370586/148666010-f00b362e-46cf-45fd-9747-43e5e6e1e5c5.png)

**Which version was it on?**
Latest Gamebanana build to this day

**Application ran from exe or from source?**
 - OS: Windows 64bit
 - Was the application run from source or was it the executable from gamebanana?
 -Gamebanana

**Comment by trayfellow** [comment]
your right, when i generate my sheet with the new version the sprites are all scrambled now, but it still works fine though

**Comment by EnderSpr1tz** [comment]
> 

for me it dosent. if i make a left sprite for example it scrambles with the miss sprites too

**Comment by trayfellow** [comment]
> > 
> 
> for me it dosent. if i make a left sprite for example it scrambles with the miss sprites too

i guess we should stick with 3.5 for now

**Comment by trayfellow** [comment]
update: you need to turn off clip to binding box, then the sprites shouldnt be scrambled anymore

**Comment by EnderSpr1tz** [comment]
> update: you need to turn off clip to binding box, then the sprites shouldnt be scrambled anymore

Thank you it worked <3
