### ISSUE TITLE
Psych Engine Grid Support

### ISSUE THREAD

**Issue by AbelitoGamerYT** [UncertainProd/FnF-Spritesheet-and-XML-Maker#38]
(sorry for bad english)
**Psych Engine** It is becoming more and more popular, so I see it convenient to add an option to be able to generate Icon Grids with the format used by that engine (150x150 per icon and only two of them on one grid)
I think it would be a good addition for people who use this engine (including me)

Example of Icon Grids used in Psych Engine:
![icon-face](https://user-images.githubusercontent.com/77520810/150406552-929a386e-33cd-44b6-a726-58893d40b3b2.png)

**Comment by 0-skid** [comment]
to make icons for psych you just draw over one of the existing icons, simple as that

**Comment by 0-skid** [comment]
> to make icons for psych you just draw over one of the existing icons, simple as that

icon png files*

**Comment by AbelitoGamerYT** [comment]
The offsets exist

> to make icons for psych you just draw over one of the existing icons, simple as that

**Comment by 0-skid** [comment]
> The offsets exist
> 
> > to make icons for psych you just draw over one of the existing icons, simple as that
> 
> 

what

**Comment by AbelitoGamerYT** [comment]
> what

I will repost this with a better explanation
