### ISSUE TITLE
Uploading Certain Images Crashes The Generator

### ISSUE THREAD

**Issue by GrimTheDragonLord** [UncertainProd/FnF-Spritesheet-and-XML-Maker#47]
**Describe the bug**
Everytime I try to upload PNG images to the generator it closes the application after saying "Importing Sprite Frames..." for a few seconds

**To Reproduce**
1. Open the generator
2. Try to upload PNG images
3. The generator says "Importing Sprite Frames..." for a few seconds 
4. Watch the application close on itself

**Expected behavior**
Uploaded PNG's are supposed to show up on the generator and NOT crash

**Which version was it on?**
Most recent version

**Application ran from exe or from source?**
EXE, I downloaded it from gamebanana
https://gamebanana.com/tools/7136

**Comment by GrimTheDragonLord** [comment]
https://user-images.githubusercontent.com/101131318/160947474-ad9b4afa-1fc7-4081-aad5-6819761e99c5.mp4

**Comment by GrimTheDragonLord** [comment]
Still having trouble with this even after the update. The ONLY images I cant upload are ones with too much black in them for some reason?

Such as these... These cannot be uploaded for some reason as shown in the video.
![Idle1](https://user-images.githubusercontent.com/101131318/177262085-8fa63105-e079-49a5-9559-96b0140cf718.png)
![idle1](https://user-images.githubusercontent.com/101131318/177262132-5266043c-2e61-4c37-8578-3707f5fb1a4d.png)

**Comment by UncertainProd** [comment]
This should be fixed now on v4.2.5. It looks like these images were stored in a non-rgba format, which seemed to be causing an error, but it should hopefully work now.
