### ISSUE TITLE
error with building

### ISSUE THREAD

**Issue by thedirptastic** [UncertainProd/FnF-Spritesheet-and-XML-Maker#5]
i'm on a mac and i get this error when building. i am on the latest version of python and on macos 10.13.6

Traceback (most recent call last):
  File "xmlpngUI.py", line 8, in <module>
    import xmlpngengine
  File "/Users/user/Downloads/FnF-Spritesheet-and-XML-Maker-master/xmlpngengine.py", line 16, in <module>
    def add_pose_numbers(pose_arr:list[str]):
TypeError: 'type' object is not subscriptable

**Comment by UncertainProd** [comment]
You can try with the code from the branch named "for_older_python_versions" which should still work with new python versions. Link: [https://github.com/UncertainProd/FnF-Spritesheet-and-XML-Maker/tree/for_older_python_versions](https://github.com/UncertainProd/FnF-Spritesheet-and-XML-Maker/tree/for_older_python_versions)
