### ISSUE TITLE
Generate Psych Engine Grid Option

### ISSUE THREAD

**Issue by AbelitoGamerYT** [UncertainProd/FnF-Spritesheet-and-XML-Maker#54]
Pysch engine uses a different icon grid system, where each icon set is a separate png (300x150) and looks like this:

![image](https://user-images.githubusercontent.com/77520810/166838652-c0cd0729-6d7f-472b-94c7-fccd07c89474.png)
Although it is already possible to use the icons generated by the program, you still have to select a classic icon grid and then cut them, which can become tedious. **An option where you only have to select the 2 icons and export them in this format** would be very useful to skip this process and get an accurate result

More and more mods are made with this engine, so it would be a good addition to the program.

Also, **less and less mods use the icon grid format that vanilla friday night funkin uses**, and this option could be used with other engines as well, or just to show the icons separately.

This post is an improved version of this other one I did in the past: #38 
I did this because I explained myself in a bad way and no one was going to notice the change if I edited it

**Comment by 0-skid** [comment]
again, just draw over bf's icons. that simple

**Comment by UncertainProd** [comment]
You can now in v4.2.1 by clicking the checkbox labelled 'Psych Engine mode'. Then you need to upload the 2 icons and it'll join them.
