### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by minecraftmc22** [UncertainProd/FnF-Spritesheet-and-XML-Maker#56]
**Describe the bug**

**To Reproduce**

The exact steps that were followed to cause the issue

**Expected behavior**
A clear and concise description of what was expected to happen.

**Screenshots**

![Screenshot 2022-06-24 22-55-26](https://user-images.githubusercontent.com/108140728/175561901-da8c65e7-6d0d-4c76-ad49-a39036c5ffcf.png)
![Screenshot 2022-06-24 22-55-36](https://user-images.githubusercontent.com/108140728/175561933-5c20be21-b9cb-4d8f-8e9e-e989c796876a.png)

**Which version was it on?**
The version number of the tool this bug was found on.

4.2.3

**Application ran from exe or from source?**
 - OS: windows 7 X64
 - EXE

 - Was the application run from source or was it the executable from gamebanana?
 - from gamebanana

**Comment by UncertainProd** [comment]
The gamebana exe only works on windows 10 and above, you can try running it from source instead
