### ISSUE TITLE
Crashing on multiple versions

### ISSUE THREAD

**Issue by EdSomePeople** [UncertainProd/FnF-Spritesheet-and-XML-Maker#73]
It crashes if I import any spites on linux and when i was on windows it crashed when I click generator same with the web version.
the sprites I'm trying to use are roughly 447 by 1036 pixels, so they a bit tall but I've seen it work with much bigger sprites.
this is the sprite that the rest are sized around.
![idle1](https://github.com/user-attachments/assets/30faa553-00a9-40f1-9d7a-6ecaba18af2c)

**Comment by UncertainProd** [comment]
It looks like this image has a bit of corrupted data inside it. I can see the crash happen when I use this image, however I managed to use something like https://compress-or-die.com/repair to fix that corrupted data and then the image seems to work
